import { describe, expect, it } from "vitest";
import { DatabaseContext } from "../../src/persistence/db.js";
import { executeTask } from "../../src/runner/dispatch.js";
import { WorkflowRunner } from "../../src/runner/runner.js";
import { discoverCanvas } from "../../src/canvas/discovery.js";

const terminal = (running = true, attention = false) => discoverCanvas({ epoch: "e", canvas: { nodes: [{ id: "n", kind: "terminal", terminal: { id: "t", nodeId: "n", name: "T", agentType: "x", floorName: "ground", isManager: false, isRunning: running, isLive: true, needsAttention: attention, preview: [] } }], connections: [] } });
const workflow: any = { version: 2, name: "p0", workspace: { id: "w", floor: "ground" }, topology: { mode: "off" }, actors: { a: { label: "A", nodeId: "n" } }, flows: { main: { entry: "loop", nodes: { loop: { type: "foreach", source: "children", flow: "child", concurrency: 2, onComplete: "done" }, done: { type: "terminal", status: "completed" } } }, child: { entry: "work", nodes: { work: { type: "task", actor: "a", outcomes: { ok: "finish" } }, finish: { type: "terminal", status: "completed" } } } } };

describe("P0 runtime reproductions", () => {
  it("runs foreach children in bounded batches", async () => { let active = 0; let maxActive = 0; const runner = new WorkflowRunner({ workflow, children: async () => ["1", "2", "3"], dispatch: async () => { active++; maxActive = Math.max(maxActive, active); await new Promise(r => setTimeout(r, 5)); active--; return { outcome: "ok" }; } }); expect(await runner.runWorkItem("w", "parent")).toBe("completed"); expect(maxActive).toBe(2); });
  it("persists the current token and resumes from it after recreation", async () => { const db = new DatabaseContext(); let calls = 0; const w: any = { ...workflow, flows: { main: { entry: "first", nodes: { first: { type: "task", actor: "a", outcomes: { ok: "second" } }, second: { type: "task", actor: "a", outcomes: { ok: "done" } }, done: { type: "terminal", status: "completed" } } } } }; const first = new WorkflowRunner({ workflow: w, db, dispatch: async () => { calls++; if (calls === 2) throw new Error("process stopped"); return { outcome: "ok" }; } }); await expect(first.runWorkItem("w", "item")).rejects.toThrow("process stopped"); expect(db.db.prepare("SELECT node_id FROM tokens WHERE id='token-item'").get()).toEqual({ node_id: "second" }); const second = new WorkflowRunner({ workflow: w, db, dispatch: async () => ({ outcome: "ok" }) }); expect(await second.resume("run-item")).toBe("completed"); });
  it("retries invalid markers and then pauses without sending an edge", async () => { const sent: string[] = []; let attempts = 0; const result = await executeTask({ actor: "a", outcomes: ["ok"], discovery: terminal(), actors: { a: { key: "a", label: "A", nodeId: "n" } }, send: async (_id, text) => { sent.push(text); }, capture: async () => { attempts++; return "no marker"; }, maxInvalidResultRetries: 2 }); expect(result.status).toBe("PAUSE_INVALID_RESULT"); expect(attempts).toBe(3); expect(sent.length).toBe(5); });
});
